export const environment = {
  production: true,
  apiServer: 'https://api.ondgo.ng/api',
  idServer: 'https://identity.ondgo.ng',
  returnUrl: 'https://airline.ondgo.ng',
  useBackend: true,
  apiLocal: '/api',
  clientId: 'AirlineAngularClient',
  scope: 'onDgoApi openid profile offline_access',
  responseType: 'id_token token',
  apiUploadFolder: 'http://192.168.1.19/api/uploads',
  b1Server: 'http://localhost:39930/api',
  prompt: 'none',
  userPermission: true,
  transportType: 0,

  data: '',
  hubUrl: '',
  logLevel: '',
  isLogLevelDebugEnabled: false,
  isLogLevelWarningEnabled: false,
  appFooter: '',
  reportDesignerUrl: '',
};
